image: debian/buster
environment:
  repo: docker.io/alexeldeib
  image: az-local-pvc
packages:
  - curl
  - gpg
  - containerd.io
  - docker-ce
  - docker-ce-cli 
secrets:
  - 7bb48981-fc03-4344-bae3-736c99f94f49 # docker_user
  - 21bdadaa-095c-4968-9a6e-ce9b795042b4 # docker_pass
sources:
  - https://github.com/alexeldeib/az-local-pvc
repositories:
- docker: https://download.docker.com/linux/debian stretch stable 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
tasks:
  - install: |
      set -o errexit
      set -o nounset
      set -o pipefail
      DISTRO="$(cat /etc/os-release | grep CODENAME | cut -d'=' -f2)"
      echo $DISTRO
  - build: |
      set -o errexit
      set -o nounset
      set -o pipefail
      
      sudo mount -t tmpfs -o size=4G /dev/null /dev/shm
      sleep 2
      sudo nohup dockerd --bip 172.18.0.1/16 </dev/null >/dev/null 2>&1 &

      cat ~/.docker_pass | sudo docker login -u $(cat ~/.docker_user) --password-stdin
      TAG=$(date -Ihours | tr :+ -)
      echo "TAG: ${TAG}"
      sudo docker build -t ${REPO}/${IMAGE}:${TAG} .
      sudo docker tag -t ${REPO}/${IMAGE}:latest .
      sudo docker push ${REPO}/${IMAGE}:${TAG}
      sudo docker push ${REPO}/${IMAGE}:latest
