image: archlinux
environment:
  repo: docker.io/alexeldeib
  image: az-local-pvc
packages:
  - docker
secrets:
  - 7bb48981-fc03-4344-bae3-736c99f94f49 # docker_user
  - 21bdadaa-095c-4968-9a6e-ce9b795042b4 # docker_pass
sources:
  - https://github.com/alexeldeib/az-local-pvc
environment:

tasks:
  - install: |
      set -o errexit
      set -o nounset
      set -o pipefail

      # See https://todo.sr.ht/~sircmpwn/builds.sr.ht/223 for why this is
      # needed.
      sudo mount -t tmpfs -o size=4G /dev/null /dev/shm
      sleep 2
      sudo nohup dockerd --bip 172.18.0.1/16 </dev/null >/dev/null 2>&1 &
      sudo usermod -aG docker $(whoami)
  - build: |
      set -o errexit
      set -o nounset
      set -o pipefail
      
      cat ~/.docker_pass | sudo docker login -u $(cat ~/.docker_user) --password-stdin
      TAG=$(date -Ihours | tr :+ -)
      echo "TAG: ${TAG}"
      sudo docker build -t ${REPO}/${IMAGE}:${TAG} .
      sudo docker tag -t ${REPO}/${IMAGE}:latest .
      sudo docker push ${REPO}/${IMAGE}:${TAG}
      sudo docker push ${REPO}/${IMAGE}:latest
