image: debian/buster
packages:
  - curl
secrets:
  - 7bb48981-fc03-4344-bae3-736c99f94f49 # docker_user
  - 21bdadaa-095c-4968-9a6e-ce9b795042b4 # docker_pass
sources:
  - https://github.com/alexeldeib/az-local-pvc
environment:
  docker_version: 19.03.8~3-0
  container_version: 1.2.6-3
tasks:
  - install: |
      set -o errexit
      set -o nounset
      set -o pipefail

      curl -sL "https://download.docker.com/linux/debian/dists/buster/pool/stable/amd64/containerd.io_${containerd_version}_amd64.deb" -o containerd.io.deb
      curl -sL "https://download.docker.com/linux/debian/dists/buster/pool/stable/amd64/docker-ce-cli_${docker_version}~debian-buster_amd64.deb" -o docker-ce-cli.io.deb
      curl -sL "https://download.docker.com/linux/debian/dists/buster/pool/stable/amd64/docker-ce_${docker_version}~debian-buster_amd64.deb" -o docker-ce.io.deb

      sudo dpkg -i containerd.io.deb
      sudo dpkg -i docker-ce-cli.io.deb
      sudo dpkg -i docker-ce.io.deb
